name: .NET Test Providers

on:
  workflow_dispatch:
  schedule:
    - cron: '40 5 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore DailyDesktop.Tests dependencies
      run: dotnet restore DailyDesktop.Tests/DailyDesktop.Tests.csproj
    - name: Build DailyDesktop.Tests
      run: dotnet build DailyDesktop.Tests --no-restore
    - name: Test DailyDesktop.Tests.TestProviders
      run: dotnet test --filter ClassName=DailyDesktop.Tests.TestProviders --no-build --verbosity normal --logger "console;verbosity=detailed"
